"""add_auth0_fields_to_user

Revision ID: 276b5b0c86ed
Revises: a19ac9f4b530
Create Date: 2025-01-07 12:08:44.620431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276b5b0c86ed'
down_revision: Union[str, None] = 'a19ac9f4b530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'name')
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###
