"""add_vector_id_messages

Revision ID: 4986d1653a7e
Revises: d4193dec4d0c
Create Date: 2025-01-13 12:25:00.480119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4986d1653a7e'
down_revision: Union[str, None] = 'd4193dec4d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('vector_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'vector_id')
    # ### end Alembic commands ###
