"""add_auth0_fields_to_user

Revision ID: 7807d3ae38e0
Revises: 276b5b0c86ed
Create Date: 2025-01-07 12:17:17.136903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7807d3ae38e0'
down_revision: Union[str, None] = '276b5b0c86ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
