"""add_edited_at_to_messages

Revision ID: 8028fffbe5ad
Revises: 4986d1653a7e
Create Date: 2025-01-14 13:19:39.344423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8028fffbe5ad'
down_revision: Union[str, None] = '4986d1653a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'edited_at')
    # ### end Alembic commands ###
