"""Add channel owner and description

Revision ID: a19ac9f4b530
Revises: 
Create Date: 2025-01-06 18:22:45.873089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19ac9f4b530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('description', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channels', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'owner_id')
    op.drop_column('channels', 'description')
    # ### end Alembic commands ###
