"""add_file_uploads

Revision ID: d4193dec4d0c
Revises: ddf2c24545f5
Create Date: 2025-01-12 00:15:07.713516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4193dec4d0c'
down_revision: Union[str, None] = 'ddf2c24545f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_uploads_message_id', 'file_uploads', ['message_id'], unique=False)
    op.create_index('idx_file_uploads_uploaded_at', 'file_uploads', ['uploaded_at'], unique=False)
    op.create_index('idx_file_uploads_uploaded_by', 'file_uploads', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_index('idx_file_uploads_uploaded_by', table_name='file_uploads')
    op.drop_index('idx_file_uploads_uploaded_at', table_name='file_uploads')
    op.drop_index('idx_file_uploads_message_id', table_name='file_uploads')
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
