"""remove_join_code_column

Revision ID: ddf2c24545f5
Revises: 9fc612a29cc9
Create Date: 2025-01-11 15:08:16.255800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf2c24545f5'
down_revision: Union[str, None] = '9fc612a29cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'join_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('join_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
